import { DateContextProvider } from "@/context/DateProvider";
import "./globals.scss";

import Sidebar from "@/components/layout/sidebar";
import Header from "@/components/layout/header";

import styles from "./page.module.scss";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="ko">
      <body>
        <DateContextProvider>
          <main className={styles.main}>
            <Header />
            <section className={styles.section}>
              <Sidebar />
              {children}
            </section>
          </main>
        </DateContextProvider>
      </body>
    </html>
  );
}
